spring:
  application:
    name: video_streaming
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB



minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: myvideos

video:
  temp:
    directory: C:\Users\fabdirashid\Documents\JAVA CORE\videos_temp\temp_videos

server:
  port: 9080
